a=("rose","jasmine","sunflower","dahlia","lotus","daisy")
print(a)
print(type(a))
print(len(a))
b=tuple((8,3,5,6,1,2))
print(b)
print(a[3])
print(a[-2])
print(a[2:4])
print(a[-5:-1])
print("lotus"in a)
print("lotus"not in a)
print("tulip"in a)
print("tulip"not in a)
x=list(a)
print(x)
x.append("hibscus")
print(x)
a=tuple(x)
print(a)
x.remove("daisy")
print(x)
for i in a:
    print(i)
z=a+b
print(z)
print(a*2)
print(a.count("rose"))