x=("football","cricket","volleyball","chess","basketball")
print(x)
print(type(x))
print(len(x))
print(x[3])
print(x[-2])
print(x[2:4])
print(x[-4:-2])
print("cricket"in x)
print("cricket"not in x)
print("carroms"in x)
print("carroms"not in x)
a=list(x)
print(a)
a.append("swimming")
print(a)
x=tuple(a)
print(x)
a.remove("volleyball")
print(a)
x=tuple(a)
for i in x:
    print(i)
y=tuple((2,6,1,4))
print(y)
b=x+y
print(b)
print(x*3)
k=y.count(6)
print(k)
